// <auto-generated />
using System;
using KassenLager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KassenLager.Data.Migrations
{
    [DbContext(typeof(KassenLagerDbContext))]
    [Migration("20261004102843_AddOrders")]
    partial class AddOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("KassenLager.Core.Domain.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleNumberKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ean")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleNumberKey")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("Model");

                    b.HasIndex("UnitId");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.BranchIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerDeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CustomerDeviceSentOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerDeviceSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReturnMovementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovementId")
                        .IsUnique();

                    b.HasIndex("ReturnMovementId")
                        .IsUnique();

                    b.ToTable("BranchIssues", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackingType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Kassenrechner",
                            SortOrder = 10,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Kassenrechner All-in-One / Backshop",
                            SortOrder = 20,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Hub",
                            SortOrder = 30,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Bedienermonitor (Touchmonitor)",
                            SortOrder = 40,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Kundenmonitor (Kundenanzeige)",
                            SortOrder = 50,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Tischscanner mit Waage",
                            SortOrder = 60,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Tischscanner ohne Waage",
                            SortOrder = 70,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Waage",
                            SortOrder = 80,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Bondrucker",
                            SortOrder = 90,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Geldlade",
                            SortOrder = 100,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Handscanner",
                            SortOrder = 110,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "EC-Terminal",
                            SortOrder = 120,
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Kabel",
                            SortOrder = 130,
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Geldladen-Ersatzteile",
                            SortOrder = 140,
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Verbrauchs- und Verschleißmaterial",
                            SortOrder = 150,
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Sonstiges",
                            SortOrder = 160,
                            TrackingType = 2
                        });
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Kunde 1"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Kunde 2"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Kunde 3"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Kunde 4"
                        });
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumberKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StateChangedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumberKey");

                    b.HasIndex("ArticleId", "SerialNumberKey")
                        .IsUnique()
                        .HasFilter("\"IsVoided\" = 0");

                    b.HasIndex("CustomerId", "State");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnchangedRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAt");

                    b.ToTable("ImportLogs", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.MinimumStock", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArticleId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("MinimumStocks", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReversalOfId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("ReversalOfId")
                        .IsUnique();

                    b.HasIndex("ArticleId", "CustomerId");

                    b.ToTable("Movements", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("OrderId", "ArticleId")
                        .IsUnique();

                    b.ToTable("OrderLines", (string)null);
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Stück"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rolle"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Packung"
                        });
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Article", b =>
                {
                    b.HasOne("KassenLager.Core.Domain.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KassenLager.Core.Domain.Unit", "Unit")
                        .WithMany("Articles")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.BranchIssue", b =>
                {
                    b.HasOne("KassenLager.Core.Domain.Movement", "Movement")
                        .WithOne("BranchIssue")
                        .HasForeignKey("KassenLager.Core.Domain.BranchIssue", "MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KassenLager.Core.Domain.Movement", "ReturnMovement")
                        .WithMany()
                        .HasForeignKey("ReturnMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Movement");

                    b.Navigation("ReturnMovement");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Device", b =>
                {
                    b.HasOne("KassenLager.Core.Domain.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KassenLager.Core.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.MinimumStock", b =>
                {
                    b.HasOne("KassenLager.Core.Domain.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KassenLager.Core.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Movement", b =>
                {
                    b.HasOne("KassenLager.Core.Domain.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KassenLager.Core.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KassenLager.Core.Domain.Device", "Device")
                        .WithMany("Movements")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KassenLager.Core.Domain.OrderLine", "OrderLine")
                        .WithMany("Movements")
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KassenLager.Core.Domain.Movement", "ReversalOf")
                        .WithOne("ReversedBy")
                        .HasForeignKey("KassenLager.Core.Domain.Movement", "ReversalOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("Customer");

                    b.Navigation("Device");

                    b.Navigation("OrderLine");

                    b.Navigation("ReversalOf");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Order", b =>
                {
                    b.HasOne("KassenLager.Core.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.OrderLine", b =>
                {
                    b.HasOne("KassenLager.Core.Domain.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KassenLager.Core.Domain.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Device", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Movement", b =>
                {
                    b.Navigation("BranchIssue");

                    b.Navigation("ReversedBy");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.OrderLine", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("KassenLager.Core.Domain.Unit", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
